import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { TrendingUp, TrendingDown, Database, Shield, Layers, Users } from 'lucide-react';
import { staggerContainer, staggerItem } from '../components/PageEnter';

const MONO: React.CSSProperties = { fontFamily: '"IBM Plex Mono", monospace' };

const SOURCE_COLORS: Record<string, string> = {
  'Bloomberg':          '#000000',
  'Reuters':            '#FF6200',
  'Wall St. Journal':   '#004276',
  'Financial Times':    '#FCD0B1',
  'CNBC':               '#005594',
  'MarketWatch':        '#2E2E2E',
  'Yahoo Finance':      '#6001D2',
  "Barron's":           '#B22222',
  'Seeking Alpha':      '#1A5276',
  'Motley Fool':        '#EB5757',
  'Benzinga':           '#00B4D8',
  'Morningstar':        '#CF0A2C',
};

const CREDIBILITY_TIERS = [
  {
    label: 'High',
    color: 'var(--accent)',
    bg:    'rgba(34,197,94,0.1)',
    range: '80 – 100',
    desc:  'Institutional-grade outlets with editorial standards: Bloomberg, Reuters, WSJ, FT, CNBC.',
    sources: ['Bloomberg', 'Reuters', 'Wall St. Journal', 'Financial Times', 'CNBC'],
  },
  {
    label: 'Medium',
    color: '#d97706',
    bg:    'rgba(217,119,6,0.1)',
    range: '60 – 79',
    desc:  'Established financial media with broad coverage: MarketWatch, Yahoo Finance, Seeking Alpha.',
    sources: ['MarketWatch', 'Yahoo Finance', 'Seeking Alpha', "Barron's"],
  },
  {
    label: 'Low',
    color: 'var(--text-muted)',
    bg:    'rgba(255,255,255,0.04)',
    range: '0 – 59',
    desc:  'Aggregators, syndicated wires, and niche publications.',
    sources: ['Benzinga', 'Motley Fool', 'Morningstar'],
  },
];

const SENTIMENT_SCALE = [
  { range: '+0.35 → +1.0', label: 'Strongly Bullish', icon: '▲▲', color: '#16a34a', bg: 'rgba(22,163,74,0.12)' },
  { range: '+0.05 → +0.34', label: 'Bullish',          icon: '▲',  color: 'var(--accent)', bg: 'rgba(34,197,94,0.1)' },
  { range: '−0.04 → +0.04', label: 'Neutral',          icon: '●',  color: '#d97706', bg: 'rgba(217,119,6,0.1)' },
  { range: '−0.34 → −0.05', label: 'Bearish',          icon: '▼',  color: 'var(--red)', bg: 'rgba(239,68,68,0.1)' },
  { range: '−1.0 → −0.35', label: 'Strongly Bearish',  icon: '▼▼', color: '#b91c1c', bg: 'rgba(185,28,28,0.12)' },
];

const STEPS = [
  {
    num: '01',
    icon: <Database className="h-5 w-5" />,
    title: 'Ingest',
    body: 'Every few minutes, articles are pulled from three parallel source feeds: Finnhub company news, curated RSS feeds, and NewsAPI. Duplicates are detected by normalised URL and silently dropped.',
  },
  {
    num: '02',
    icon: <Shield className="h-5 w-5" />,
    title: 'Score',
    body: 'Each article receives two scores: a credibility score based on the publication tier, and a sentiment score generated by an NLP model that weighs the headline and summary.',
  },
  {
    num: '03',
    icon: <Layers className="h-5 w-5" />,
    title: 'Group',
    body: 'Articles are grouped by their primary ticker and ranked by recency. The top article in each group becomes the featured StreamCard; the rest appear as compact headlines below.',
  },
  {
    num: '04',
    icon: <Users className="h-5 w-5" />,
    title: 'Discuss',
    body: 'Logged-in users can create threads, leave comments, and cast Bullish / Bearish votes. The community signal sits alongside the automated sentiment to give a human-in-the-loop layer.',
  },
];

function GaugeMini({ score }: { score: number }) {
  const cx = 50, cy = 46, r = 36;
  const angleDeg = 180 - (score + 1) * 90;
  const angleRad = (angleDeg * Math.PI) / 180;
  const ex = cx + r * Math.cos(angleRad);
  const ey = cy - r * Math.sin(angleRad);
  const filledPath = `M ${cx - r} ${cy} A ${r} ${r} 0 0 1 ${ex.toFixed(2)} ${ey.toFixed(2)}`;
  const trackPath  = `M ${cx - r} ${cy} A ${r} ${r} 0 0 1 ${cx + r} ${cy}`;
  const nr = r - 8;
  const color = score >= 0.05 ? '#16a34a' : score <= -0.05 ? '#b91c1c' : '#d97706';
  return (
    <svg viewBox="0 0 100 58" width={100} height={58}>
      <path d={trackPath} fill="none" stroke="var(--bg-elevated)" strokeWidth="7" />
      <motion.path d={filledPath} fill="none" stroke={color} strokeWidth="7"
        initial={{ pathLength: 0 }} animate={{ pathLength: 1 }}
        transition={{ duration: 1.2, ease: 'easeOut', delay: 0.3 }} />
      <motion.line
        x1={cx} y1={cy} x2={cx} y2={cy - nr}
        stroke={color} strokeWidth="2" strokeLinecap="round"
        initial={{ rotate: 90 }} animate={{ rotate: 90 - angleDeg }}
        style={{ originX: `${cx}px`, originY: `${cy}px` }}
        transition={{ duration: 1.2, ease: 'easeOut', delay: 0.3 }}
      />
      <circle cx={cx} cy={cy} r={3.5} fill={color} />
      <text x={cx} y={cy - 12} textAnchor="middle" fontSize="11" fontWeight="900"
        fill="var(--text-primary)" fontFamily='"IBM Plex Mono", monospace'>
        {score > 0 ? `+${score.toFixed(2)}` : score.toFixed(2)}
      </text>
    </svg>
  );
}

export function HowItWorks() {
  return (
    <motion.div
      className="max-w-2xl mx-auto py-4 space-y-12"
      variants={staggerContainer}
      initial="hidden"
      whileInView="show"
      viewport={{ once: true }}
    >
      {/* Page header */}
      <motion.div variants={staggerItem} className="border-b-2 pb-3" style={{ borderColor: 'var(--text-primary)' }}>
        <p className="text-[9px] font-bold uppercase tracking-widest mb-1" style={{ color: 'var(--text-muted)', ...MONO }}>
          Documentation
        </p>
        <h1 className="text-3xl font-black uppercase leading-none" style={{ color: 'var(--text-primary)', ...MONO }}>
          How SentimentSignal Works
        </h1>
        <p className="mt-3 text-sm leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
          SentimentSignal aggregates real-time financial news, scores each article for credibility
          and sentiment, then surfaces the signal so you can trade with context.
        </p>
      </motion.div>

      {/* Pipeline steps */}
      <motion.div variants={staggerItem}>
        <div className="flex items-center gap-2 pb-3 mb-6 border-b-2" style={{ borderColor: 'var(--text-primary)' }}>
          <h2 className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--text-primary)', ...MONO }}>
            The Pipeline
          </h2>
        </div>
        <div className="space-y-0">
          {STEPS.map((step, i) => (
            <motion.div
              key={step.num}
              variants={staggerItem}
              whileHover={{ x: 4, transition: { duration: 0.12 } }}
              className="flex gap-5 py-5 border-b"
              style={{ borderColor: 'var(--border)' }}
            >
              {/* Step number */}
              <div className="shrink-0 flex flex-col items-center gap-2">
                <span
                  className="text-[10px] font-black tabular-nums"
                  style={{ color: 'var(--accent)', ...MONO }}
                >
                  {step.num}
                </span>
                {i < STEPS.length - 1 && (
                  <div className="w-px flex-1 min-h-[32px]" style={{ backgroundColor: 'var(--border)' }} />
                )}
              </div>
              {/* Content */}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-2">
                  <span style={{ color: 'var(--accent)' }}>{step.icon}</span>
                  <h3 className="text-sm font-black uppercase tracking-widest" style={{ color: 'var(--text-primary)', ...MONO }}>
                    {step.title}
                  </h3>
                </div>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
                  {step.body}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* Data sources */}
      <motion.div variants={staggerItem}>
        <div className="flex items-center gap-2 pb-3 mb-6 border-b-2" style={{ borderColor: 'var(--text-primary)' }}>
          <h2 className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--text-primary)', ...MONO }}>
            Data Sources
          </h2>
        </div>
        <p className="text-sm mb-5 leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
          Articles are pulled from three parallel feeds — Finnhub, curated RSS, and NewsAPI — and
          merged into a single deduplicated stream. Every outlet is whitelisted and assigned a fixed
          credibility tier.
        </p>
        <div className="flex flex-wrap gap-2">
          {Object.entries(SOURCE_COLORS).map(([name, bg]) => (
            <span
              key={name}
              className="inline-block px-3 py-1.5 text-[10px] font-black uppercase tracking-widest"
              style={{ backgroundColor: bg, color: '#ffffff', ...MONO }}
            >
              {name}
            </span>
          ))}
        </div>
      </motion.div>

      {/* Sentiment scoring */}
      <motion.div variants={staggerItem}>
        <div className="flex items-center gap-2 pb-3 mb-6 border-b-2" style={{ borderColor: 'var(--text-primary)' }}>
          <h2 className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--text-primary)', ...MONO }}>
            Sentiment Scoring
          </h2>
        </div>

        <p className="text-sm mb-6 leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
          Every article headline and summary is passed through a financial NLP model and assigned a
          score from <span style={{ color: '#b91c1c' }}>−1.0 (Strongly Bearish)</span> to{' '}
          <span style={{ color: '#16a34a' }}>+1.0 (Strongly Bullish)</span>.
        </p>

        {/* Visual scale */}
        <div className="space-y-2 mb-8">
          {SENTIMENT_SCALE.map(row => (
            <div
              key={row.label}
              className="flex items-center gap-3 px-3 py-2.5"
              style={{ backgroundColor: row.bg }}
            >
              <span className="text-base font-black w-8 text-center" style={{ color: row.color }}>{row.icon}</span>
              <span className="flex-1 text-[11px] font-black uppercase tracking-widest" style={{ color: row.color, ...MONO }}>
                {row.label}
              </span>
              <span className="text-[10px] tabular-nums" style={{ color: row.color, ...MONO }}>{row.range}</span>
            </div>
          ))}
        </div>

        {/* Gauge demo */}
        <div className="border p-5" style={{ borderColor: 'var(--border)', backgroundColor: 'var(--bg-surface)' }}>
          <p className="text-[9px] font-bold uppercase tracking-widest mb-4" style={{ color: 'var(--text-muted)', ...MONO }}>
            Gauge examples
          </p>
          <div className="flex items-end justify-around gap-4 flex-wrap">
            {[-0.75, -0.2, 0, 0.35, 0.8].map(s => (
              <div key={s} className="flex flex-col items-center gap-1">
                <GaugeMini score={s} />
                <span className="text-[9px] tabular-nums" style={{ color: 'var(--text-muted)', ...MONO }}>
                  {s > 0 ? `+${s.toFixed(2)}` : s.toFixed(2)}
                </span>
              </div>
            ))}
          </div>
        </div>
      </motion.div>

      {/* Credibility tiers */}
      <motion.div variants={staggerItem}>
        <div className="flex items-center gap-2 pb-3 mb-6 border-b-2" style={{ borderColor: 'var(--text-primary)' }}>
          <h2 className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--text-primary)', ...MONO }}>
            Credibility Tiers
          </h2>
        </div>
        <p className="text-sm mb-6 leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
          Not all news is equal. Each publication is permanently assigned to one of three tiers based
          on editorial independence, fact-checking practices, and financial journalism reputation.
        </p>
        <div className="space-y-4">
          {CREDIBILITY_TIERS.map(tier => (
            <div
              key={tier.label}
              className="border-l-4 pl-4 py-3"
              style={{ borderColor: tier.color, backgroundColor: tier.bg }}
            >
              <div className="flex items-center gap-3 mb-1">
                <span className="text-[11px] font-black uppercase tracking-widest" style={{ color: tier.color, ...MONO }}>
                  {tier.label} Credibility
                </span>
                <span className="text-[10px] tabular-nums" style={{ color: tier.color, ...MONO }}>
                  Score {tier.range}
                </span>
              </div>
              <p className="text-xs mb-3 leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
                {tier.desc}
              </p>
              <div className="flex flex-wrap gap-1.5">
                {tier.sources.map(s => (
                  <span
                    key={s}
                    className="text-[9px] font-bold uppercase tracking-widest px-2 py-0.5 border"
                    style={{ borderColor: tier.color, color: tier.color, ...MONO }}
                  >
                    {s}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Community signal */}
      <motion.div variants={staggerItem}>
        <div className="flex items-center gap-2 pb-3 mb-6 border-b-2" style={{ borderColor: 'var(--text-primary)' }}>
          <h2 className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--text-primary)', ...MONO }}>
            Community Signal
          </h2>
        </div>
        <p className="text-sm mb-6 leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
          The machine score tells you what an algorithm thinks. The community score tells you what
          informed investors actually believe. SentimentSignal layers both.
        </p>
        <div className="grid grid-cols-2 gap-4">
          <div className="border p-4" style={{ borderColor: 'var(--border)', borderLeft: '3px solid var(--accent)' }}>
            <div className="flex items-center gap-2 mb-2">
              <TrendingUp className="h-4 w-4" style={{ color: 'var(--accent)' }} />
              <span className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--accent)', ...MONO }}>
                Bullish Vote
              </span>
            </div>
            <p className="text-xs leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
              Signals you believe the market will react positively to this story. Adds +1 to the thread's net score.
            </p>
          </div>
          <div className="border p-4" style={{ borderColor: 'var(--border)', borderLeft: '3px solid var(--red)' }}>
            <div className="flex items-center gap-2 mb-2">
              <TrendingDown className="h-4 w-4" style={{ color: 'var(--red)' }} />
              <span className="text-[10px] font-black uppercase tracking-widest" style={{ color: 'var(--red)', ...MONO }}>
                Bearish Vote
              </span>
            </div>
            <p className="text-xs leading-relaxed" style={{ color: 'var(--text-secondary)', ...MONO }}>
              Signals you believe the market will react negatively. Adds −1 to the thread's net score. You can retract or switch at any time.
            </p>
          </div>
        </div>
      </motion.div>

      {/* Footer CTA */}
      <motion.div variants={staggerItem} className="border-t pt-8" style={{ borderColor: 'var(--border)' }}>
        <div className="flex items-center gap-6 flex-wrap">
          <Link
            to="/app"
            className="text-[10px] font-black uppercase tracking-widest border-2 px-4 py-2 transition-colors hover:bg-[var(--accent)] hover:border-[var(--accent)] hover:text-black"
            style={{ borderColor: 'var(--accent)', color: 'var(--accent)', ...MONO }}
          >
            Open Feed →
          </Link>
          <Link
            to="/app/discuss"
            className="text-[10px] font-bold uppercase tracking-widest transition-colors hover:text-[var(--accent)]"
            style={{ color: 'var(--text-muted)', ...MONO }}
          >
            Go to Discuss
          </Link>
        </div>
      </motion.div>
    </motion.div>
  );
}
